cargo-features = ["codegen-backend"]

[package]
name = "nanai-gna-dll-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "nanai_gna_dll_rs"
path = "src/lib.rs"

[[bin]]
name = "nanai-gna-dll-rs"
path = "src/main.rs"

[dependencies]
libloading = "0.8"
thiserror = "2"

[dev-dependencies]
tempfile = "3"
